name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.1"
version = "0.9.1"
rev = "7492a451c214f0f3f26dc3b3631cff370a53d601"
hash = "sha256-VCxsFs+97QjLOglhNSFQzd7siQbDjuN6anmrAjCbnFc="
subdir = "./fuel-core"
lock = "./Cargo.lock"
