name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.1.1"
version = "0.1.1"
rev = "7521c7cba529f25d56ddf27b2b61b8eaef071116"
hash = "sha256-9VVfKLklRjXHqN3AkzRjeezd4WSid/jv5+aGsI74eps="
subdir = "./fuel-core"
lock = "./Cargo.lock"
