name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.6.4"
version = "0.6.4"
rev = "a450b05d835ff050bfd6ad1654617047984da83d"
hash = "sha256-Z8qzyXlBIvdW8kuFcTQqEFtzTpgbz/0kUD4IU9c221c="
subdir = "./fuel-core"
lock = "./Cargo.lock"
