name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.7"
version = "0.9.7"
rev = "56ba5e36ece9adde21009d9b392813b0d24d859b"
hash = "sha256-5w5OBrWMk+5zPnHCWmo3LbqJ7LsKUSExLowe2r30CYA="
subdir = "./fuel-core"
lock = "./Cargo.lock"
