name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.3.2"
version = "0.3.2"
rev = "03e2ae95d323a623468ca059a059f9f6d7668afc"
hash = "sha256-zoCyOy5XNtFidHPw7KiFNqjy5iEzPH1EnLZuh+ThMmk="
subdir = "./fuel-core"
lock = "./Cargo.lock"
