name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.6"
version = "0.9.6"
rev = "9db8d330907ba69bd5a8fbddd39d83524ec9f6b5"
hash = "sha256-bqi3x+aK+w9T+vqA9/5r7t3TIq5U0oHGKVUtNBLhf64="
subdir = "./fuel-core"
lock = "./Cargo.lock"
