name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.8"
version = "0.9.8"
rev = "783db68f047510f64c3af1ea60a9f0e7e7c7b263"
hash = "sha256-e5YHs6NkYaHVUbwN9G+T9ilay1O6QXtFth3ErzDf6iI="
subdir = "./fuel-core"
lock = "./Cargo.lock"
