name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.6.2"
version = "0.6.2"
rev = "8080217c6d967f2a2a8cc4814a1f175db2d6d7b4"
hash = "sha256-ElTMCra+UAVuZZHU1EB4JnQ2QUV8tZU1t5xBAAcakto="
subdir = "./fuel-core"
lock = "./Cargo.lock"
