name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.3"
version = "0.9.3"
rev = "4848d8ddaa3d5817314c17c9cda5c81c92719a74"
hash = "sha256-F0i/k/2l0kWyOsozm3G6ki4+rXCY+iHzZHS7BaTMcPE="
subdir = "./fuel-core"
lock = "./Cargo.lock"
