name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.6.1"
version = "0.6.1"
rev = "2af86bc703fa5693581950fcf9402f0e074da81e"
hash = "sha256-uLSXcHimji9RjW/ipLep+cCn3Q2M2zRWbXGZGMrh1e4="
subdir = "./fuel-core"
lock = "./Cargo.lock"
