name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.6.3"
version = "0.6.3"
rev = "670d16379ed1420061fc9772043b86e7101a3a6e"
hash = "sha256-dceUSGEb8oG0QIvWM4HI3eoorKGKSkPTzmwODVjWiUM="
subdir = "./fuel-core"
lock = "./Cargo.lock"
