name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.9.5"
version = "0.9.5"
rev = "ae309759529fc2dda1b736e8204a2264136bb0ad"
hash = "sha256-YaMZvEcYOkBnj7pqu3OugLa3CFXxAaA7Zpa4XaOKM4Y="
subdir = "./fuel-core"
lock = "./Cargo.lock"
