name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.1.2"
version = "0.1.2"
rev = "07f1a3ffe2d7904c51b6c87daa0198d45ea2fdd8"
hash = "sha256-VQ2fv7Hz+kFSOzfxCEqiEfoi+GR+IQfPPM8x/vo5SbU="
subdir = "./fuel-core"
lock = "./Cargo.lock"
