name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.10.1"
version = "0.10.1"
rev = "a0351c241754f670470cbf0aa5bb743582b038d1"
hash = "sha256-qReSFYtSZieoHiCSsy9kdgCxUImbJIYpAMakeHT1HXk="
subdir = "./fuel-core"
lock = "./Cargo.lock"
