name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.4.2"
version = "0.4.2"
rev = "94c8ce7e7ef4b808db907d3c2508b6b005b6bf43"
hash = "sha256-MQQR7iG4dCIHMKv3bgtAjTebEyeB9+8R4o/Javs4F9o="
subdir = "./fuel-core"
lock = "./Cargo.lock"
