name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.10.0"
version = "0.10.0"
rev = "749db6cfbbb3554025d5f4a39dda4e36022c421f"
hash = "sha256-MYF6KASLxinXumJxwFdXXUjLQnPZAWohuTB8HgYvYcs="
subdir = "./fuel-core"
lock = "./Cargo.lock"
