name = "fuel-core"
repo = "https://github.com/fuellabs/fuel-core"
tag = "v0.3.1"
version = "0.3.1"
rev = "c41b8138cb8a09f1c98ea1f36777bc440d0c983a"
hash = "sha256-RpyYD8JY8FqzNRobfmduoM3N+kJ5/s6nTwYSsscV51Q="
subdir = "./fuel-core"
lock = "./Cargo.lock"
