name: "fuel"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  nix-fmt-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix fmt -- --check ./

  nix-flake-check:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --no-update-lock-file

  nix-build:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - package: fuel-core
          - package: fuel-gql-cli
          - package: forc
          - package: forc-explore
          - package: forc-fmt
          - package: forc-lsp
          - package: sway-vim
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: mitchmindtree-fuellabs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --print-build-logs --no-update-lock-file .#${{ matrix.job.package }}
